# Generated by Django 3.1.1 on 2020-10-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='timeUsage',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('activity', models.TextField()),
                ('startTime', models.TextField()),
                ('endTime', models.TextField()),
                ('duration', models.TextField()),
                ('note', models.TextField()),
                ('tag', models.TextField()),
            ],
        ),
    ]
