# Generated by Django 3.1.1 on 2020-10-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeusage',
            name='activity',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='timeusage',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='timeusage',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timeusage',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timeusage',
            name='note',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='timeusage',
            name='startTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timeusage',
            name='tag',
            field=models.CharField(max_length=60),
        ),
    ]
